# Template for Streamlit secrets
# Rename this file to 'secrets.toml' and add your actual API keys

# The Movie Database (TMDB) API key
# Get yours at https://www.themoviedb.org/settings/api
TMDB_API_KEY = "your_tmdb_api_key_here" 